### ISSUE TITLE
distributed.core annoying messages when n_jobs > 1

### ISSUE THREAD

**Issue by grayskripko** [magnusfurugard/featuretoolsR#13]
I get tens of 
```r
distributed.core - INFO - Event loop was unresponsive in Nanny for 1276.34s.  
This is often caused by long-running GIL-holding functions or moving large chunks of data. 
This can cause timeouts and instability.
```

Have you met these warnings? Do you know how to deal with them?
Spent many hours and tried different approaches with python log settings, featuretools settings, reticulate capturing these print messages, ```capture.output()``` and ```sink``` in R

**Comment by magnusfurugard** [comment]
Thanks for filing the issue. I don't get them. Can you add some reprex + versions?

**Comment by grayskripko** [comment]
I'll reopen the issue in case I manage to find time to get you a reprex
