### ISSUE TITLE
Readme code does not work

### ISSUE THREAD

**Issue by AtharKharal** [magnusfurugard/featuretoolsR#2]
I have just gone through the code as given in Readme last line 
tidy <- tidy_feature_matrix(ft_matrix, remove_nzv = T, nan_is_na = T)

gives following:

Removing near zero variance variables
Error in as.vector(x, mode) : 
  cannot coerce type 'environment' to vector of type 'any'

Any help please?

**Comment by magnusfurugard** [comment]
Can you provide your `sessionInfo()`?

**Comment by AtharKharal** [comment]
hi, sorry for the late response from my side. The issue was not with the package, my PC was virus infected, as soon as I updated anti-virus , it has disappeared. 
By the way, how do you see comparing featuretoolsR vs. vtreat from Win-vector? Can we combine the best of both packages?

**Comment by magnusfurugard** [comment]
I'm glad the issue worked itself out.

> By the way, how do you see comparing featuretoolsR vs. vtreat from Win-vector? Can we combine the best of both packages?

I don't see they're comparable at all. One is for cleaning / preparing data, whereas `featuretoolsR` is used for creating features. They do work well together (`featuretoolsR` --> `vtreat`).

Closing this issue.
