### ISSUE TITLE
Reload R-session after featuretools installation

### ISSUE THREAD

**Issue by magnusfurugard** [magnusfurugard/featuretoolsR#24]
Currently the library can't be used until the R session restarted after running `install_featuretools()`. 

Upon successful Featuretools installation, unload and reload R-session. Perhaps something like:

```
cat("Reloading featuretoolsR\n")
unloadNamespace("featuretoolsR")
.rs.restartR() -> .; rm(.)
library(featuretoolsR)
```

(Not sure if this is allowed by CRAN, should be checked first)

**Comment by magnusfurugard** [comment]
To add in next update:
```
# Reload library
unloadNamespace("featuretoolsR")
. <- .rs.restartR(afterRestartCommand = 'library(featuretoolsR)')
```

**Comment by grayskripko** [comment]
I have a poorly explained error solving with a restart

** testing if installed package can be loaded
+-------------------------+
|   featuretoolsR 0.4.3   |
+-------------------------+
v Using Featuretools 0.6.1
* DONE (featuretoolsR)
In R CMD INSTALL
The following may have incorrect capitalization specification:

featuretoolsRcoercing argument of type 'character' to logicalError in if (any(install_checks)) { : 
  missing value where TRUE/FALSE needed

**Comment by magnusfurugard** [comment]
Reprex?

I don’t get the issue on any of my test machines and I don’t recognize the code. 

(Also, you should update Featuretools to 0.9.1)

**Comment by grayskripko** [comment]
I don't know how to reprex it :) Let's left it as is

**Comment by magnusfurugard** [comment]
#34
