### ISSUE TITLE
featuretoolsR::add_relationship new signiture

### ISSUE THREAD

**Issue by grayskripko** [magnusfurugard/featuretoolsR#25]
the new signature of `featuretoolsR::add_relationship(entityset, parent_set, child_set, parent_idx, child_idx)` break my previos code. I suggest to change it to `featuretoolsR::add_relationship(entityset, parent_set, child_set, parent_idx, child_idx=parent_idx)`

**Comment by magnusfurugard** [comment]
Thanks for filing the issue. 

Before this hits 1.0.0 there are going to be breaking changes to the API. 

You suggestion however is not a bad one. Let’s try and fit it in the next release.

**Comment by magnusfurugard** [comment]
#34
