### ISSUE TITLE
library("featuretoolsR")  error

### ISSUE THREAD

**Issue by AWalkInClouds** [magnusfurugard/featuretoolsR#35]
> library("featuretoolsR")
╔═════════════════════════╗
║   featuretoolsR 0.4.4   ║
╚═════════════════════════╝
错误: package or namespace load failed for ‘featuretoolsR’:
 attachNamespace()里算'featuretoolsR'时.onAttach失败了，详细内容：
  调用: py_get_attr_impl(x, name, silent)
  错误: AttributeError: module 'featuretools' has no attribute '__version__'

**Comment by praktiskt** [comment]
What version of `featuretools` (the python module) do you have installed? Did you run `featuretoolsR::install_featuretools()`?

**Comment by AWalkInClouds** [comment]
Run featuretoolsR::install_featuretools(), OK!
Thank you!

**Comment by praktiskt** [comment]
Cool, assuming that solved it for you. Closing.
