### ISSUE TITLE
add_relationship signature

### ISSUE THREAD

**Issue by grayskripko** [magnusfurugard/featuretoolsR#8]
I met a problem trying to execute add_relationship() and I solved it only after reading the python featuretools documentation. https://docs.featuretools.com/generated/featuretools.Relationship.html#featuretools.Relationship

1. It's hard to understand where to place parent and child set arguments when arguments called "set1" and "set2". I suggest to call them as in the original version: parent_variable, child_variable or maybe parent_set, child_set.

2. Is it possible to have 2 separate arguments for parent_idx and child_idx in order to avoid aligning your entity column names?

**Comment by magnusfurugard** [comment]
Partially resolved in 3bf8ae262a50526cba6f22dcc772af27ab1e600f
